const { Router } = require("express");
const { body } = require("express-validator");
const ctrl = require("../controllers/authController");
const validate = require("../middleware/validate");
const { authLimiter } = require("../middleware/rateLimiter");
const r = Router();
r.post("/signup", authLimiter, [body("name").notEmpty(), body("email").isEmail(), body("password").isLength({ min: 6 })], validate, ctrl.signup);
r.post("/login",  authLimiter, [body("email").isEmail(), body("password").notEmpty()], validate, ctrl.login);
r.post("/google", authLimiter, ctrl.googleLogin);
module.exports = r;
